name: Deploy workflow

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    build:

        runs-on: self-hosted
    
        steps:
        - uses: actions/checkout@v3
        - name: Use Node.js 21.x
          uses: actions/setup-node@v3
          with:
            node-version: 21.x
        - run: npm install
        - run: node index.js